"""Remediation Playbooks - 17 IOC-type playbooks with technical, governance, and evidence steps.
Auto-generated by AI agent on detection create.
SLA auto-override for KEV actively_exploited.
"""
from dataclasses import dataclass, field
from typing import Optional

@dataclass
class PlaybookStep:
    step: str
    detail: str

@dataclass
class Playbook:
    ioc_type: str
    title: str
    severity: str
    sla_hours: int
    assignee_role: str
    technical_steps: list[PlaybookStep]
    governance_steps: list[PlaybookStep]
    evidence_required: list[str]
    sla_override_condition: Optional[str] = None
    sla_override_hours: Optional[int] = None

# ── 17 Playbooks ──
PLAYBOOKS: dict[str, Playbook] = {

"leaked_api_key": Playbook(
    ioc_type="aws_access_key|github_pat|openai_api_key|stripe_live_key|google_api_key",
    title="Leaked API Key Response",
    severity="CRITICAL", sla_hours=2, assignee_role="Security Lead",
    technical_steps=[
        PlaybookStep("Revoke key immediately", "Revoke in provider console: AWS IAM / GitHub Settings / Stripe Dashboard"),
        PlaybookStep("Audit API calls", "Review all API calls made with that key since creation date"),
        PlaybookStep("Treat repo as compromised", "Rotate ALL secrets in same repo - assume full exposure"),
        PlaybookStep("Install pre-commit hooks", "Add GitLeaks/TruffleHog pre-commit hook to prevent recurrence"),
        PlaybookStep("Full history scan", "Run TruffleHog --full-history on all branches and commit history"),
    ],
    governance_steps=[
        PlaybookStep("Check for unauthorized charges", "May trigger billing incident if API quota consumed"),
        PlaybookStep("Timeline documentation", "Document timeline for potential breach notification assessment"),
        PlaybookStep("Data access review", "Review data access scope - if PII-adjacent escalate to legal"),
    ],
    evidence_required=[
        "Screenshot of key revocation confirmation in provider console",
        "Log audit export showing no unauthorized access in exposure window",
        "New key creation confirmation (different prefix/format)",
        "Pre-commit hook installation proof (git config output)",
    ],
    sla_override_condition="Key confirmed active - unauthorized charges found",
    sla_override_hours=1,
),

"credential_combo": Playbook(
    ioc_type="email_password_combo|breachdirectory_combo|username_password_combo",
    title="Credential Combo - Dark Web Exposure",
    severity="CRITICAL", sla_hours=4, assignee_role="IT Admin",
    technical_steps=[
        PlaybookStep("Force immediate password reset", "Reset all matched accounts via IdP (Okta/Entra/Azure AD)"),
        PlaybookStep("Check login history", "Review IdP for unauthorized access in last 30 days"),
        PlaybookStep("Invalidate all active sessions", "Server-side session invalidation - not just password reset"),
        PlaybookStep("Enforce MFA", "Enable MFA if not active - mandatory, not optional"),
        PlaybookStep("BreachDirectory scope check", "Cross-check BreachDirectory for plaintext password to assess scope"),
    ],
    governance_steps=[
        PlaybookStep("Notify affected employees", "Clear, non-alarming guidance to affected accounts"),
        PlaybookStep("Executive escalation", "If executive accounts affected, escalate to CISO"),
        PlaybookStep("Breach response documentation", "Document incident per internal breach response policy"),
    ],
    evidence_required=[
        "Password reset confirmation from IdP admin panel",
        "Session invalidation log export",
        "MFA enrollment confirmation per affected account",
        "Login history audit showing no unauthorized access",
    ],
    sla_override_condition="Active login detected using compromised credentials",
    sla_override_hours=1,
),

"session_cookie_dump": Playbook(
    ioc_type="session_auth_tokens|jwt_token",
    title="Session Token / Cookie Dump - Live Hijack Risk",
    severity="CRITICAL", sla_hours=1, assignee_role="Dev + SecOps",
    technical_steps=[
        PlaybookStep("Invalidate ALL active sessions", "Server-side session store flush - not just the exposed token"),
        PlaybookStep("Rotate session secret / JWT key", "Immediate signing key rotation - invalidates all existing tokens"),
        PlaybookStep("Force re-authentication", "All users across all devices must re-login"),
        PlaybookStep("Search auth logs", "Identify session usage from unfamiliar IPs in last 24h"),
        PlaybookStep("Implement IP/device binding", "Add IP-binding or device fingerprinting for high-value accounts"),
    ],
    governance_steps=[
        PlaybookStep("Executive escalation", "If session belonged to exec or admin -> CISO immediately"),
        PlaybookStep("Data access assessment", "Determine what data was accessible via the hijacked session"),
        PlaybookStep("Breach notification assessment", "Assess obligation if sensitive data was accessible"),
    ],
    evidence_required=[
        "Session store cleared confirmation (Redis FLUSHALL or DB truncate log)",
        "New signing key deployment confirmation",
        "Auth log showing no anomalous sessions post-rotation",
    ],
),

"ransomware_leak": Playbook(
    ioc_type="ransomware_leak|darkweb_mention",
    title="Ransomware / Leak Site Mention - Existential Risk",
    severity="CRITICAL", sla_hours=1, assignee_role="CISO + Legal",
    technical_steps=[
        PlaybookStep("Escalate to CISO + IR team", "Do NOT wait for confirmation - act immediately on mention"),
        PlaybookStep("Preserve forensic evidence", "Snapshot + memory dump BEFORE any remediation"),
        PlaybookStep("Assess data scope", "Determine what data is referenced - scope alleged exfiltration"),
        PlaybookStep("Network segmentation lockdown", "Disable lateral movement NOW - isolate affected segments"),
        PlaybookStep("Verify backup integrity", "Check backups immediately - ransomware targets backups first"),
    ],
    governance_steps=[
        PlaybookStep("Activate crisis comms plan", "Internal + external messaging ready before anything leaks publicly"),
        PlaybookStep("Breach notification prep", "GDPR 72h, CCPA, state law timelines - begin preparation now"),
        PlaybookStep("Legal hold", "All relevant systems and communications - do not delete anything"),
        PlaybookStep("Ransom payment assessment", "Legal and regulatory dimensions - OFAC sanction implications"),
        PlaybookStep("Board notification", "Executive communication drafted and approved"),
    ],
    evidence_required=[
        "Forensic image of affected systems (pre-remediation)",
        "IR report confirming scope + containment",
        "Network segmentation confirmation (firewall rule audit)",
        "Backup integrity verification report",
        "Legal counsel engagement letter on file",
    ],
),

"phishing_domain": Playbook(
    ioc_type="domain|url",
    title="Phishing Domain / Typosquat - Brand Impersonation",
    severity="HIGH", sla_hours=8, assignee_role="Security Team",
    technical_steps=[
        PlaybookStep("Submit takedown request", "Registrar abuse form + ICANN complaint"),
        PlaybookStep("Block at email + DNS gateway", "Split-horizon DNS block + email gateway rule"),
        PlaybookStep("Submit to phishing databases", "PhishTank + Google Safe Browsing + Microsoft SmartScreen"),
        PlaybookStep("Add to SIEM blocklist", "CEF export auto-propagates via ArgusWatch"),
        PlaybookStep("Monitor 10 permutations", "Watch variant domains for 30 days"),
    ],
    governance_steps=[
        PlaybookStep("Alert customers + employees", "Targeted communication about the phishing domain"),
        PlaybookStep("Trademark claim filing", "If brand infringement is clear - legal action"),
        PlaybookStep("Check if employees clicked", "Review email gateway logs for click-throughs"),
    ],
    evidence_required=[
        "Abuse report submission confirmation (ticket number)",
        "DNS block confirmation from network team",
        "PhishTank submission URL",
        "30-day monitoring rule set in ArgusWatch",
    ],
),

"malicious_ip": Playbook(
    ioc_type="ipv4|ipv6",
    title="Malicious IP (C2 / Botnet) - Active C2 Risk",
    severity="HIGH", sla_hours=4, assignee_role="Network SecOps",
    technical_steps=[
        PlaybookStep("Block at firewall/WAF", "Inbound AND outbound - bidirectional block required"),
        PlaybookStep("Search for existing connections", "SIEM/endpoint logs - 30-day lookback for this IP"),
        PlaybookStep("Isolate any connected endpoints", "Assume compromised - initiate IR on connected endpoints"),
        PlaybookStep("Add to SIEM blocklist", "CEF export via ArgusWatch auto-propagates"),
        PlaybookStep("Report to AbuseIPDB", "Contributes back to community intelligence"),
    ],
    governance_steps=[
        PlaybookStep("Initiate IR if endpoints connected", "Don't wait - connection = compromise assumption"),
        PlaybookStep("Law enforcement documentation", "Connection history for potential referral"),
    ],
    evidence_required=[
        "Firewall block rule confirmation (rule ID + effective date)",
        "SIEM query results showing no active connections post-block",
        "Endpoint isolation confirmation if any connected",
    ],
),

"github_code_leak": Playbook(
    ioc_type="infra_code_leaks|github_pat_classic|github_fine_grained_pat",
    title="Internal Code / Config on GitHub - IP Theft Risk",
    severity="HIGH", sla_hours=2, assignee_role="Dev Lead",
    technical_steps=[
        PlaybookStep("Delete repo or file immediately", "Use GitHub API for speed - do not wait"),
        PlaybookStep("Contact GitHub security", "security@github.com for cache removal"),
        PlaybookStep("Rotate ALL referenced credentials", "Treat as fully exposed - rotate everything in the file"),
        PlaybookStep("Full history TruffleHog scan", "All branches and all commit history"),
        PlaybookStep("Add .gitignore + pre-commit hooks", "GitLeaks + secrets scanning in CI/CD pipeline"),
    ],
    governance_steps=[
        PlaybookStep("Audit repo access", "Who had access - internal contributors and forks"),
        PlaybookStep("Check GitHub forks + stars", "Assess how widely the content has been cached"),
        PlaybookStep("Legal assessment", "If trade secrets exposed - IP theft assessment"),
    ],
    evidence_required=[
        "Repo deletion confirmation or file removal commit hash",
        "GitHub security team response confirmation",
        "All rotated credentials with new values deployed",
        "CI/CD secrets scanning enabled (screenshot)",
    ],
),

"employee_email_darkweb": Playbook(
    ioc_type="email",
    title="Employee Email on Dark Web Combo List",
    severity="HIGH", sla_hours=8, assignee_role="IT Admin",
    technical_steps=[
        PlaybookStep("Notify affected employee", "Clear, non-alarming direct communication"),
        PlaybookStep("Cross-check password match", "Does exposed password match any corporate account?"),
        PlaybookStep("Force corporate password reset", "Regardless of password match status"),
        PlaybookStep("Review account activity", "Suspicious logins in last 90 days via IdP"),
        PlaybookStep("Add to 30-day watchlist", "ArgusWatch monitoring for follow-up activity"),
    ],
    governance_steps=[
        PlaybookStep("Executive escalation", "If executive email - CISO and priority watch"),
        PlaybookStep("Monthly breach report", "Add to audit trail for compliance reporting"),
    ],
    evidence_required=[
        "Employee notification sent (email confirmation)",
        "Password reset confirmation from IdP",
        "Login history audit - no anomalies confirmed",
        "Watchlist entry created in ArgusWatch with 30-day expiry",
    ],
    sla_override_condition="Exposed password matches corporate IdP - active credential stuffing detected",
    sla_override_hours=2,
),

"malware_hash": Playbook(
    ioc_type="md5|sha256|sha1",
    title="Malware Hash - Active Campaign in Customer Sector",
    severity="MEDIUM", sla_hours=24, assignee_role="SecOps",
    technical_steps=[
        PlaybookStep("Confirm hash on endpoints", "EDR scan (CrowdStrike / Defender) across all endpoints"),
        PlaybookStep("Quarantine + isolate if infected", "Isolate endpoint before any remediation action"),
        PlaybookStep("Push updated AV/EDR signatures", "Force signature update across all endpoints"),
        PlaybookStep("Cross-reference CISA KEV", "If hash linked to KEV CVE - patch immediately"),
        PlaybookStep("Subnet-wide scan", "Full subnet scan with updated signatures"),
    ],
    governance_steps=[
        PlaybookStep("Full IR process if infected", "Active infection = full incident response"),
        PlaybookStep("ISAC sharing", "If customer participates in ISAC - share indicator"),
    ],
    evidence_required=[
        "EDR scan results showing no detections on all endpoints",
        "AV signature update deployment confirmation",
        "Patch deployment confirmation if KEV cross-reference found",
    ],
),

"cve_tech_stack": Playbook(
    ioc_type="cve_id",
    title="CVE in Tech Stack (CISA KEV)",
    severity="HIGH", sla_hours=72, assignee_role="IT + Dev",
    technical_steps=[
        PlaybookStep("Confirm affected version", "Exact version match in asset inventory required"),
        PlaybookStep("Apply vendor patch", "Test in staging first if time allows - CISA deadline binding"),
        PlaybookStep("Check KEV exploitation timeline", "Compare dateAdded against your exposure window"),
        PlaybookStep("Apply compensating control if unpatchable", "WAF rule or network-level control immediately"),
        PlaybookStep("Verify at 72h re-check", "ArgusWatch auto-schedules re-scan"),
    ],
    governance_steps=[
        PlaybookStep("Add to vuln management register", "KEV designation = prioritized remediation"),
        PlaybookStep("Risk acceptance if delayed", "If maintenance window needed - CISO sign-off required"),
        PlaybookStep("Cyber insurance notification", "Some policies require KEV remediation notification"),
    ],
    evidence_required=[
        "Patch deployment confirmation with version number",
        "ArgusWatch 72h re-check result: VERIFIED_CLOSED",
        "WAF rule confirmation if compensating control used",
        "Vulnerability management register updated with remediation date",
    ],
    sla_override_condition="KEV actively_exploited:true",
    sla_override_hours=24,
),

"pii_financial_exposed": Playbook(
    ioc_type="financial_identity",
    title="Financial Data / PII Exposed - Regulatory Breach Trigger",
    severity="CRITICAL", sla_hours=2, assignee_role="CISO + Legal",
    technical_steps=[
        PlaybookStep("Identify source and scope", "Which system leaked, how much data, affected individuals"),
        PlaybookStep("Preserve evidence chain", "Forensic integrity for regulators - chain of custody"),
        PlaybookStep("Revoke access to affected systems", "Pending full investigation"),
        PlaybookStep("Scan for additional exposure", "Same IOC pattern - check for more exposure"),
    ],
    governance_steps=[
        PlaybookStep("Notify legal immediately", "GDPR 72h clock starts from moment of awareness"),
        PlaybookStep("Assess notification obligation", "Which individuals, which jurisdictions"),
        PlaybookStep("Prepare regulatory notification", "DPA/ICO/FTC with required data points"),
        PlaybookStep("Notify affected individuals", "GDPR/CCPA required disclosures - document all"),
        PlaybookStep("File regulatory report", "Within mandated window - document everything"),
    ],
    evidence_required=[
        "Legal counsel engagement confirmation",
        "Regulatory notification filed + reference number",
        "Affected individual notifications sent (batch confirmation)",
        "Data source secured + access controls audited",
        "Board notification documented (if material breach)",
    ],
),

"exposed_infrastructure": Playbook(
    ioc_type="ipv4",
    title="Exposed Internal Infrastructure (Shodan)",
    severity="MEDIUM", sla_hours=48, assignee_role="IT Admin",
    technical_steps=[
        PlaybookStep("Confirm via Shodan scan output", "Verify exposure from enrichment data in ArgusWatch"),
        PlaybookStep("Apply firewall rule", "Restrict public access immediately"),
        PlaybookStep("Patch if CVE applicable", "Cross-reference CISA KEV for the exposed service"),
        PlaybookStep("Audit access logs", "Check for unauthorized access during exposure window"),
        PlaybookStep("Update asset inventory", "Correct exposure classification"),
    ],
    governance_steps=[
        PlaybookStep("Asset register update", "Exposure date + remediation date for audit trail"),
        PlaybookStep("Process review flag", "Systemic exposure pattern warrants configuration management review"),
    ],
    evidence_required=[
        "Firewall rule applied - rule ID and effective date",
        "Shodan re-scan showing no longer public (post-remediation)",
        "Access log audit - no unauthorized access confirmed",
    ],
),

"oauth_token_exposed": Playbook(
    ioc_type="google_oauth_token|slack_bot_token|slack_user_token",
    title="OAuth / SaaS Access Token Exposed - MFA Bypass Class",
    severity="CRITICAL", sla_hours=1, assignee_role="Dev + SecOps",
    technical_steps=[
        PlaybookStep("Revoke token in SaaS provider", "Google/MS/Slack/GitHub OAuth apps console immediately"),
        PlaybookStep("Assess token scope", "Read-only vs write vs admin changes response urgency significantly"),
        PlaybookStep("Audit API activity logs", "SaaS audit log for token activity since issuance"),
        PlaybookStep("Identify exposure source", "CI/CD env var, hardcoded, .env committed - fix root cause"),
        PlaybookStep("Rotate all app tokens", "All tokens for the same application/integration"),
    ],
    governance_steps=[
        PlaybookStep("Classify data access", "Token scope + data classification = notification obligation assessment"),
        PlaybookStep("Full account compromise treatment", "If write/admin scope - treat as full account compromise"),
        PlaybookStep("OAuth app audit", "Remove unused authorizations - full OAuth inventory"),
    ],
    evidence_required=[
        "Token revocation confirmation in SaaS admin panel",
        "SaaS audit log showing no unauthorized activity",
        "New token issued (if integration still needed) + stored in secrets vault",
    ],
),

"saas_misconfiguration": Playbook(
    ioc_type="saas_misconfiguration",
    title="SaaS Misconfiguration - Public Storage Bucket",
    severity="HIGH", sla_hours=4, assignee_role="DevOps + IT Admin",
    technical_steps=[
        PlaybookStep("Make bucket private immediately", "aws s3api put-public-access-block - one command"),
        PlaybookStep("Inventory all bucket objects", "Assess what data was exposed during the window"),
        PlaybookStep("Check access logs", "External reads/downloads during exposure window"),
        PlaybookStep("Enable bucket versioning + logging", "Going forward - make default policy"),
        PlaybookStep("Audit all other storage", "Same misconfiguration across all buckets/containers"),
    ],
    governance_steps=[
        PlaybookStep("Classify exposed data", "PII/financial = notification obligations"),
        PlaybookStep("Add Storage CSPM policy", "Prevent recurrence via CSPM tool"),
        PlaybookStep("Security policy update", "Mandate access review before storage deployment"),
    ],
    evidence_required=[
        "Bucket ACL/policy showing private access only",
        "Access log review - no unauthorized downloads confirmed",
        "CSPM scan showing no public storage remaining",
    ],
),

"data_exfiltration": Playbook(
    ioc_type="data_exfil_anomaly",
    title="Data Exfiltration Anomaly - Active Transfer",
    severity="CRITICAL", sla_hours=2, assignee_role="SOC Lead + CISO",
    technical_steps=[
        PlaybookStep("Identify source endpoint + destination IP", "Immediate triage - is transfer still active?"),
        PlaybookStep("Block destination IP at firewall", "If still transferring - block immediately"),
        PlaybookStep("Isolate source endpoint", "Network isolation - assume compromised"),
        PlaybookStep("Capture NetFlow/packet data", "Forensic capture before any cleanup"),
        PlaybookStep("Classify transferred data", "What was transferred - data classification audit"),
    ],
    governance_steps=[
        PlaybookStep("Activate IR retainer", "Do not investigate without counsel - legal privilege"),
        PlaybookStep("Breach notification assessment", "Classification determines GDPR/CCPA notification"),
        PlaybookStep("Preserve forensic evidence", "Chain of custody for all evidence"),
        PlaybookStep("Board notification", "If material - public company stock disclosure may be required"),
    ],
    evidence_required=[
        "NetFlow data showing transfer stopped",
        "Endpoint isolation confirmation",
        "IR report confirming scope + data classification",
        "Legal hold documentation",
    ],
),

"privileged_account_anomaly": Playbook(
    ioc_type="privileged_account",
    title="Privileged Account Anomaly - Admin Compromise",
    severity="HIGH", sla_hours=4, assignee_role="Security Lead",
    technical_steps=[
        PlaybookStep("Force session termination immediately", "Privileged account - no delay tolerated"),
        PlaybookStep("Reset privileged credentials + MFA", "Force re-enrollment - new device required"),
        PlaybookStep("Review admin action audit trail", "Persistence mechanisms, new accounts, policy changes"),
        PlaybookStep("Check for Golden Ticket artifacts", "Pass-the-Hash / Pass-the-Ticket in AD environments"),
        PlaybookStep("Enhanced logging 30 days", "All privileged accounts - elevated monitoring"),
    ],
    governance_steps=[
        PlaybookStep("CISO notification immediately", "Privileged compromise is always board-level event"),
        PlaybookStep("Insider threat investigation", "If internal source - HR + Legal involvement"),
        PlaybookStep("PAM policy update", "Access certification review and PAM hardening"),
    ],
    evidence_required=[
        "Session termination confirmation from IdP",
        "Credential reset + MFA re-enrollment proof",
        "Admin audit trail export - no unauthorized changes confirmed",
        "Enhanced logging enabled confirmation (30-day window)",
    ],
),

"shadow_it": Playbook(
    ioc_type="shadow_it",
    title="Shadow IT Discovery - Unmanaged Asset",
    severity="MEDIUM", sla_hours=120, assignee_role="IT Admin",
    technical_steps=[
        PlaybookStep("Identify asset owner and purpose", "Don't kill it blind - find the business need first"),
        PlaybookStep("Assess security posture", "Patching, auth, encryption, logging status"),
        PlaybookStep("Decision: onboard or decommission", "Apply standard controls if kept"),
        PlaybookStep("Apply standard security controls", "EDR, logging, MFA, patching if onboarded"),
        PlaybookStep("Add to ArgusWatch monitoring scope", "Asset inventory + monitoring coverage"),
    ],
    governance_steps=[
        PlaybookStep("Update asset register", "SOC 2 / ISO 27001 finding - document it"),
        PlaybookStep("Policy reminder to owner", "Document for security awareness training"),
        PlaybookStep("Risk committee review", "Add to shadow IT governance review agenda"),
    ],
    evidence_required=[
        "Asset owner identified and confirmed",
        "Security assessment completed",
        "Onboarded to managed IT stack OR decommission confirmation",
        "Asset inventory updated",
    ],
),
}

def get_playbook(ioc_type: str, detection_source: str = "") -> Optional[Playbook]:
    """Get the best matching playbook for an IOC type."""
    # Direct match
    for pb_key, pb in PLAYBOOKS.items():
        if ioc_type in pb.ioc_type:
            return pb

    # Fuzzy match -  map specific IOC types to playbook categories
    type_map = {
        # API Keys -> leaked_api_key playbook
        "aws_access_key": "leaked_api_key",
        "aws_secret_key": "leaked_api_key",
        "aws_root_key": "leaked_api_key",
        "github_pat_classic": "leaked_api_key",
        "github_fine_grained_pat": "leaked_api_key",
        "github_oauth_token": "leaked_api_key",
        "github_app_token": "leaked_api_key",
        "gitlab_pat": "leaked_api_key",
        "openai_api_key": "leaked_api_key",
        "anthropic_api_key": "leaked_api_key",
        "stripe_live_key": "leaked_api_key",
        "sendgrid_api_key": "leaked_api_key",
        "google_api_key": "leaked_api_key",
        "azure_sas_token": "leaked_api_key",
        "azure_bearer": "leaked_api_key",
        "private_key": "leaked_api_key",
        "exposed_secret": "leaked_api_key",
        "twilio_account_sid": "leaked_api_key",

        # Credentials -> credential_combo playbook
        "email_password_combo": "credential_combo",
        "breachdirectory_combo": "credential_combo",
        "username_password_combo": "credential_combo",
        "email_hash_combo": "credential_combo",
        "plaintext_password": "credential_combo",
        "db_connection_string": "credential_combo",
        "remote_credential": "credential_combo",
        "ldap_dn": "credential_combo",

        # Privileged -> privileged_account_anomaly playbook
        "privileged_credential": "privileged_account_anomaly",
        "breakglass_credential": "privileged_account_anomaly",
        "golden_ticket_indicator": "privileged_account_anomaly",
        "ntlm_hash": "privileged_account_anomaly",
        "ntlm_hash_format": "privileged_account_anomaly",

        # Session tokens -> session_cookie_dump playbook
        "session_cookie": "session_cookie_dump",
        "jwt_token": "session_cookie_dump",
        "saml_assertion": "session_cookie_dump",
        "google_oauth_token": "oauth_token_exposed",
        "google_oauth_bearer": "oauth_token_exposed",
        "slack_bot_token": "oauth_token_exposed",
        "slack_user_token": "oauth_token_exposed",
        "slack_bot_oauth": "oauth_token_exposed",
        "slack_user_oauth": "oauth_token_exposed",

        # Ransomware -> ransomware_leak playbook
        "ransomware_group": "ransomware_leak",
        "ransom_note": "ransomware_leak",
        "data_auction": "ransomware_leak",

        # Network IOCs
        "ipv4": "malicious_ip",
        "ipv6": "malicious_ip",
        "domain": "phishing_domain",
        "url": "phishing_domain",
        "malicious_url_path": "phishing_domain",
        "onion_address": "phishing_domain",

        # CVE + hashes
        "cve_id": "cve_tech_stack",
        "md5": "malware_hash",
        "sha256": "malware_hash",
        "sha1": "malware_hash",
        "sha512": "malware_hash",

        # Data exfiltration
        "data_transfer_cmd": "data_exfiltration",
        "base64_exfil": "data_exfiltration",
        "sql_outfile_exfil": "data_exfiltration",
        "archive_and_exfil": "data_exfiltration",
        "csv_credential_dump": "data_exfiltration",
        "csv_pii_dump": "data_exfiltration",
        "csv_financial_dump": "data_exfiltration",
        "sql_dump_header": "data_exfiltration",
        "sql_dump_detected": "data_exfiltration",
        "sql_schema_dump": "data_exfiltration",
        "archive_sensitive_data": "data_exfiltration",
        "file_share_exfil": "data_exfiltration",

        # Infrastructure leaks
        "config_file": "github_code_leak",
        "backup_file": "github_code_leak",
        "db_config": "github_code_leak",

        # SaaS misconfig
        "s3_public_url": "exposed_infrastructure",
        "s3_bucket_ref": "exposed_infrastructure",
        "azure_blob_public": "exposed_infrastructure",
        "gcs_public_bucket": "exposed_infrastructure",
        "elasticsearch_exposed": "exposed_infrastructure",
        "open_analytics_service": "exposed_infrastructure",

        # Shadow IT
        "personal_cloud_share": "shadow_it",
        "dev_tunnel_exposed": "shadow_it",
        "rogue_dev_endpoint": "shadow_it",

        # Email
        "email": "employee_email_darkweb",
        "executive_email": "employee_email_darkweb",

        # Financial
        "visa_card": "credential_combo",
        "mastercard": "credential_combo",
        "amex_card": "credential_combo",
        "ssn": "credential_combo",
        "iban": "credential_combo",
        "swift_bic": "credential_combo",

        # Missing types
        "hash_sha256": "malware_hash",
        "github_saas_token": "leaked_api_key",
        "github_user_token": "leaked_api_key",
        "apt_group": "ransomware_leak",
        "advisory": "cve_tech_stack",
        "bitcoin_address": "credential_combo",
        "ethereum_address": "credential_combo",
        "monero_address": "credential_combo",
        "cidr_range": "malicious_ip",
        "internal_hostname": "exposed_infrastructure",
    }
    pb_key = type_map.get(ioc_type)
    if pb_key:
        return PLAYBOOKS.get(pb_key)

    # Source-based fallback
    if detection_source in ("ransomfeed",):
        return PLAYBOOKS["ransomware_leak"]
    if detection_source in ("hudsonrock", "telegram"):
        return PLAYBOOKS["session_cookie_dump"]
    if detection_source in ("shodan",):
        return PLAYBOOKS["exposed_infrastructure"]

    return PLAYBOOKS.get("credential_combo")  # default

def apply_sla_override(playbook: Playbook, detection_metadata: dict) -> tuple[str, int]:
    """Apply SLA override if conditions are met. Returns (severity, sla_hours)."""
    severity = playbook.severity
    sla = playbook.sla_hours

    # KEV actively_exploited override
    if (playbook.ioc_type == "cve_id" or "cve" in playbook.ioc_type) and \
       detection_metadata.get("actively_exploited"):
        return "CRITICAL", 24

    # Check configured override
    if playbook.sla_override_condition and playbook.sla_override_hours:
        if detection_metadata.get("override_triggered"):
            return "CRITICAL", playbook.sla_override_hours

    return severity, sla

def render_playbook_text(playbook: Playbook) -> str:
    """Render playbook as plain text for AI agent context."""
    lines = [f"PLAYBOOK: {playbook.title}",
             f"Severity: {playbook.severity} | SLA: {playbook.sla_hours}h | Assignee: {playbook.assignee_role}",
             "", "TECHNICAL STEPS:"]
    for i, s in enumerate(playbook.technical_steps, 1):
        lines.append(f"  {i}. {s.step}: {s.detail}")
    lines += ["", "GOVERNANCE / LEGAL:"]
    for i, s in enumerate(playbook.governance_steps, 1):
        lines.append(f"  {i}. {s.step}: {s.detail}")
    lines += ["", "EVIDENCE REQUIRED FOR CLOSURE:"]
    for i, e in enumerate(playbook.evidence_required, 1):
        lines.append(f"  {i}. {e}")
    if playbook.sla_override_condition:
        lines += ["", f"SLA OVERRIDE: {playbook.sla_override_condition} -> CRITICAL {playbook.sla_override_hours}h"]
    return "\n".join(lines)


# ── V12: Required exports for dashboard + enrichments router ──

IOC_TO_PLAYBOOK: dict[str, str] = {}
for _key, _pb in PLAYBOOKS.items():
    for _ioc in _pb.ioc_type.split("|"):
        IOC_TO_PLAYBOOK[_ioc.strip()] = _key
# Common short aliases
IOC_TO_PLAYBOOK.update({
    "domain": "phishing_domain",
    "url": "phishing_domain",
    "ipv4": "malicious_ip",
    "ipv6": "malicious_ip",
    "ip": "malicious_ip",
    "md5": "malware_hash",
    "sha256": "malware_hash",
    "sha1": "malware_hash",
    "email": "employee_email_darkweb",
    "cve_id": "cve_tech_stack",
})


def get_all_playbooks() -> dict:
    """Return all playbooks in dashboard-compatible format."""
    return {
        "count": len(PLAYBOOKS),
        "playbooks": [
            {
                "key": k,
                "ioc_type": v.ioc_type.split("|")[0],
                "title": v.title,
                "severity": v.severity,
                "sla_hours": v.sla_hours,
                "assignee_role": v.assignee_role,
            }
            for k, v in PLAYBOOKS.items()
        ],
    }


def get_playbook_detail(ioc_type: str) -> dict | None:
    """Return full playbook detail with dashboard-compatible field names."""
    pb = get_playbook(ioc_type)
    if not pb:
        return None
    key = IOC_TO_PLAYBOOK.get(ioc_type, ioc_type)
    return {
        "key": key,
        "ioc_type": ioc_type,
        "title": pb.title,
        "severity": pb.severity,
        "sla_hours": pb.sla_hours,
        "assignee_role": pb.assignee_role,
        "business_impact": getattr(pb, "business_impact", ""),
        "detection_sources": getattr(pb, "detection_sources", []),
        "confidence_note": getattr(pb, "confidence_note", ""),
        # Dashboard expects these exact keys:
        "steps_technical": [s.step + ": " + s.detail for s in pb.technical_steps],
        "steps_governance": [s.step + ": " + s.detail for s in pb.governance_steps],
        "evidence_required": list(pb.evidence_required) if pb.evidence_required else [],
    }
